services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mcp-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost/api
      - PORT=3000
    ports:
      - "3002:3000"
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
