# docker-compose.override.yml - Development Overrides
version: '3.8'

services:
  # Development-specific overrides
  model-router:
    environment:
      - LOG_LEVEL=DEBUG
      - DEBUG_MODE=true
    volumes:
      - ./src/model_router:/app/src:ro  # Live code reloading
    ports:
      - "8001:8001"  # Expose for direct access

  plan-management:
    environment:
      - LOG_LEVEL=DEBUG
      - AUTO_BACKUP=false
    volumes:
      - ./src/plan_management:/app/src:ro
    ports:
      - "8002:8002"

  git-worktree-manager:
    environment:
      - LOG_LEVEL=DEBUG
      - AUTO_CLEANUP=false
    volumes:
      - ./src/git_worktree:/app/src:ro
      - ./test-repos:/app/test-repos  # Test repositories
    ports:
      - "8003:8003"

  workflow-orchestrator:
    environment:
      - LOG_LEVEL=DEBUG
      - MAX_CONCURRENT_WORKFLOWS=2
    volumes:
      - ./src/workflow_orchestrator:/app/src:ro
    ports:
      - "8004:8004"

  verification-feedback:
    environment:
      - LOG_LEVEL=DEBUG
      - STRICT_VERIFICATION=false
    volumes:
      - ./src/verification_feedback:/app/src:ro
    ports:
      - "8005:8005"

  # Development database with sample data
  postgres:
    volumes:
      - ./database/sample_data.sql:/docker-entrypoint-initdb.d/99_sample_data.sql:ro
    ports:
      - "5432:5432"  # Expose for development tools

  # Development Redis with persistence disabled
  redis:
    command: redis-server --save ""
    ports:
      - "6379:6379"

  # Expose Consul UI
  consul:
    ports:
      - "8500:8500"

  # Development tools container
  dev-tools:
    profiles: [] # Remove dev profile restriction
    command: tail -f /dev/null  # Keep container running
