# Docker Compose for Cloudflare Tunnel
# This extends the main docker-compose.yml with tunnel services


services:
  # Cloudflare Tunnel Service
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: mcp-cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflare-tunnel/config.yml:/etc/cloudflared/config.yml:ro
      - ./cloudflare-tunnel/credentials.json:/etc/cloudflared/credentials.json:ro
    environment:
      - TUNNEL_METRICS=0.0.0.0:9080
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'
        reservations:
          memory: 64M
          cpus: '0.1'


networks:
  mcp-network:
    external: true
