auth_enabled: false

server:
  http_listen_port: 3100

common:
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules

<<<<<<< HEAD
  ring:
    kvstore:
      store: inmemory

=======
>>>>>>> main
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

analytics:
  reporting_enabled: false

limits_config:
  retention_period: 168h

compactor:
  working_directory: /loki/compactor

storage_config:
  boltdb:
    directory: /loki/index
  filesystem:
    directory: /loki/chunks

ingester:
  wal:
<<<<<<< HEAD
    enabled: false
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
=======
    enabled: false
>>>>>>> main
