# monitoring/prometheus.yml - Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts/rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mcp-services'
    static_configs:
      - targets: 
        - 'model-router:8001'
        - 'plan-management:8002'
        - 'git-worktree-manager:8003'
        - 'workflow-orchestrator:8004'
        - 'verification-feedback:8005'
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/metrics'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'consul'
    static_configs:
      - targets: ['consul:8500']

  # LLM Stack Services (external to RAG-agent network)
  - job_name: 'llm-ollama'
    static_configs:
      - targets: ['host.docker.internal:11434']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 15s
    
  - job_name: 'llm-qdrant'
    static_configs:
      - targets: ['host.docker.internal:6333']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 15s
    
  - job_name: 'llm-fastapi'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
