rules:
  # All tasks use z.ai GLM-4.5 as the primary model
  - match: '(?i).*(code|function|class|algorithm|programming|debug|implement|python|javascript|java|c\+\+|sql|api|refactor|optimize|bug|error|syntax|variable).*'
    model: glm-4.5
  # Complex tasks use z.ai GLM-4.5
  - match: '(?i).*(architecture|security|complex|analysis|research).*'
    model: glm-4.5
  - match: '^/analysis'
    model: glm-4.5
  # Local models for development and general use
  - match: '(?i).*(local|offline|mistral).*'
    model: deepseek-coder
  # Simple tasks also use z.ai GLM-4.5
  - match: '(?i).*(simple|quick|basic|test).*'
    model: glm-4.5
  # Default to z.ai GLM-4.5
  - match: '.*'
    model: glm-4.5
