apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-router
  template:
    metadata:
      labels:
        app: model-router
    spec:
      containers:
        - name: model-router
          image: mcp/model-router:latest
          ports:
            - containerPort: 80
