apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-orchestrator
  template:
    metadata:
      labels:
        app: workflow-orchestrator
    spec:
      containers:
        - name: workflow-orchestrator
          image: mcp/workflow-orchestrator:latest
          ports:
            - containerPort: 80
