# Cloudflare Tunnel Configuration for MCP Agent Network
# This configuration sets up tunnels for both frontend and API access

tunnel: 657508b0-1901-4e6d-b33f-3273cc8f5ab2
credentials-file: /opt/llm-stack/rag-agent/cloudflare-tunnel/credentials.json

# Ingress rules - order matters, most specific first
ingress:
  # Grafana Monitoring Dashboard (port 3005)
  - hostname: grafana.ethical-ai-insider.com
    service: http://localhost:3005
    originRequest:
      connectTimeout: 30s
      tlsTimeout: 30s
      tcpKeepAlive: 30s
      noHappyEyeballs: false
      keepAliveConnections: 10
      keepAliveTimeout: 90s
      httpHostHeader: grafana.ethical-ai-insider.com
      originServerName: grafana.ethical-ai-insider.com

  # Staff Frontend domain - Staff portal application (port 3001)
  - hostname: staff.ethical-ai-insider.com
    service: http://localhost:3001
    originRequest:
      connectTimeout: 30s
      tlsTimeout: 30s
      tcpKeepAlive: 30s
      noHappyEyeballs: false
      keepAliveConnections: 10
      keepAliveTimeout: 90s
      httpHostHeader: staff.ethical-ai-insider.com
      originServerName: staff.ethical-ai-insider.com

  # Frontend domain - Next.js application (direct connection)  
  - hostname: new.ethical-ai-insider.com
    service: http://localhost:3000
    originRequest:
      connectTimeout: 30s
      tlsTimeout: 30s
      tcpKeepAlive: 30s
      noHappyEyeballs: false
      keepAliveConnections: 10
      keepAliveTimeout: 90s
      httpHostHeader: new.ethical-ai-insider.com
      originServerName: new.ethical-ai-insider.com

  # Model Router API - Direct access to model routing service
  - hostname: model-router.ethical-ai-insider.com
    service: http://localhost:8001
    originRequest:
      connectTimeout: 30s
      tlsTimeout: 30s
      tcpKeepAlive: 30s
      noHappyEyeballs: false
      keepAliveConnections: 10
      keepAliveTimeout: 90s
      httpHostHeader: model-router.ethical-ai-insider.com
      originServerName: model-router.ethical-ai-insider.com

  # Plan Management API
  - hostname: plan-management.ethical-ai-insider.com
    service: http://localhost:8002
    originRequest:
      connectTimeout: 30s
      tlsTimeout: 30s
      tcpKeepAlive: 30s
      noHappyEyeballs: false
      keepAliveConnections: 10
      keepAliveTimeout: 90s
      httpHostHeader: plan-management.ethical-ai-insider.com
      originServerName: plan-management.ethical-ai-insider.com

  # Git Worktree Manager API
  - hostname: git-worktree.ethical-ai-insider.com
    service: http://localhost:8003
    originRequest:
      connectTimeout: 30s
      tlsTimeout: 30s
      tcpKeepAlive: 30s
      noHappyEyeballs: false
      keepAliveConnections: 10
      keepAliveTimeout: 90s
      httpHostHeader: git-worktree.ethical-ai-insider.com
      originServerName: git-worktree.ethical-ai-insider.com

  # Workflow Orchestrator API
  - hostname: workflow-orchestrator.ethical-ai-insider.com
    service: http://localhost:8004
    originRequest:
      connectTimeout: 30s
      tlsTimeout: 30s
      tcpKeepAlive: 30s
      noHappyEyeballs: false
      keepAliveConnections: 10
      keepAliveTimeout: 90s
      httpHostHeader: workflow-orchestrator.ethical-ai-insider.com
      originServerName: workflow-orchestrator.ethical-ai-insider.com

  # Verification Feedback API
  - hostname: verification-feedback.ethical-ai-insider.com
    service: http://localhost:8005
    originRequest:
      connectTimeout: 30s
      tlsTimeout: 30s
      tcpKeepAlive: 30s
      noHappyEyeballs: false
      keepAliveConnections: 10
      keepAliveTimeout: 90s
      httpHostHeader: verification-feedback.ethical-ai-insider.com
      originServerName: verification-feedback.ethical-ai-insider.com

  # Staff Service API
  - hostname: staff-api.ethical-ai-insider.com
    service: http://localhost:8006
    originRequest:
      connectTimeout: 30s
      tlsTimeout: 30s
      tcpKeepAlive: 30s
      noHappyEyeballs: false
      keepAliveConnections: 10
      keepAliveTimeout: 90s
      httpHostHeader: staff-api.ethical-ai-insider.com
      originServerName: staff-api.ethical-ai-insider.com

  # API domain - Nginx gateway for MCP services (main API gateway)
  - hostname: newapi.ethical-ai-insider.com
    service: http://localhost:80
    originRequest:
      connectTimeout: 30s
      tlsTimeout: 30s
      tcpKeepAlive: 30s
      noHappyEyeballs: false
      keepAliveConnections: 10
      keepAliveTimeout: 90s
      httpHostHeader: newapi.ethical-ai-insider.com
      originServerName: newapi.ethical-ai-insider.com

  # Catch-all rule (required) - redirect to main site
  - service: http_status:404

# Tunnel-wide settings
retries: 3
no-autoupdate: false
grace-period: 30s

# Logging configuration
loglevel: info
transport-loglevel: warn

# Metrics server (optional - for monitoring)
metrics: localhost:9080

# Edge configuration
edge-ip-version: auto

# Protocol optimization
protocol: quic

# Additional security headers for API
warp-routing:
  enabled: false