# Cloudflare Tunnel Configuration for MCP Agent Network
# This configuration sets up tunnels for both frontend and API access

tunnel: 657508b0-1901-4e6d-b33f-3273cc8f5ab2
credentials-file: /etc/cloudflared/credentials.json

# Ingress rules - order matters, most specific first
ingress:
  # Grafana Monitoring Dashboard (port 3005)
  - hostname: grafana.ethical-ai-insider.com
    service: http://grafana:3000
    originRequest:
      connectTimeout: 30s
      tlsTimeout: 30s
      tcpKeepAlive: 30s
      noHappyEyeballs: false
      keepAliveConnections: 10
      keepAliveTimeout: 90s
      httpHostHeader: grafana.ethical-ai-insider.com
      originServerName: grafana.ethical-ai-insider.com

  # Staff Frontend domain - Staff portal application (port 3001)
  - hostname: staff.ethical-ai-insider.com
    service: http://staff-frontend:3001
    originRequest:
      connectTimeout: 30s
      tlsTimeout: 30s
      tcpKeepAlive: 30s
      noHappyEyeballs: false
      keepAliveConnections: 10
      keepAliveTimeout: 90s
      httpHostHeader: staff.ethical-ai-insider.com
      originServerName: staff.ethical-ai-insider.com

  # Frontend domain - Next.js application (port 3000 internally, mapped to 3002 on host)  
  - hostname: new.ethical-ai-insider.com
    service: http://mcp-frontend:3000
    originRequest:
      connectTimeout: 30s
      tlsTimeout: 30s
      tcpKeepAlive: 30s
      noHappyEyeballs: false
      keepAliveConnections: 10
      keepAliveTimeout: 90s
      httpHostHeader: new.ethical-ai-insider.com
      originServerName: new.ethical-ai-insider.com

  # API domain - Nginx gateway for MCP services (main API gateway)
  - hostname: newapi.ethical-ai-insider.com
    service: http://nginx:80
    originRequest:
      connectTimeout: 30s
      tlsTimeout: 30s
      tcpKeepAlive: 30s
      noHappyEyeballs: false
      keepAliveConnections: 10
      keepAliveTimeout: 90s
      httpHostHeader: newapi.ethical-ai-insider.com
      originServerName: newapi.ethical-ai-insider.com

  # Catch-all rule (required) - redirect to main site
  - service: http_status:404

# Tunnel-wide settings
retries: 3
no-autoupdate: false
grace-period: 30s

# Logging configuration
loglevel: info
transport-loglevel: warn

# Metrics server (optional - for monitoring)
metrics: localhost:9080

# Edge configuration
edge-ip-version: auto

# Protocol optimization
protocol: quic

# Additional security headers for API
warp-routing:
  enabled: false
